### PR TITLE
Fix cache invalidation and add touch improvements

### PR DESCRIPTION
**Pull request by mmiszy**

### CODE REVIEW

**Comment by grEvenX** [comment]
No speccy spec? :)

**Comment by JakubJagoda** [comment]
:+1:

**Comment by grEvenX** [comment]
Please test this

**Comment by grEvenX** [comment]
Please test this

**Comment by cometcultci** [comment]
Can one of the admins verify this patch?

**Comment by grEvenX** [comment]
Please test this

**Comment by grEvenX** [comment]
Please test this

**Comment by grEvenX** [comment]
Please test this

**Pull request merged**
